  version : '3'

  services:
    frontend:
      image: subicura/guestbook-frontend:latest
      ports: 
        - 60000:3000
      environment:
        - PORT=3000 
        - GUESTBOOK_API_ADDR=backend:8000

    backend:
      image: subicura/guestbook-backend:latest
      environment: 
        - PORT=8000
        - GUESTBOOK_DB_ADDR=mongodb:27017

    mongodb:
      image: mongo:4
      ports: 
        - 27017:27017 # 기본 포트
      volumes: 
        - db_data:/data/db
        
  volumes: 
    db_data: {}      